### ISSUE TITLE
Sleepyq client unable to login

### ISSUE THREAD

**Issue by joshdreagan** [technicalpickles/sleepyq#11] opened 2020-11-19 20:37 UTC
As of today, the Sleepyq client seems to no longer be working. The following simple test:

```
from sleepyq import Sleepyq
client = Sleepyq("my_sleepiq_username", "my_sleepiq_password")
client.login()
```

results in the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jreagan/.local/lib/python3.8/site-packages/sleepyq/__init__.py", line 125, in login
    self._session.params['_k'] = r.json()['key']
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by joshdreagan** [comment] 2020-11-19 23:01
Dug into this a bit more and it looks like the '/login' request is returning a 403. I did some experimenting and it seems like they're blocking requests with a 'User-Agent': 'python-requests/2.24.0'. Which is what the Python requests library uses by default. I'm guessing that they don't like all the requests coming in from Home Assistant users... :rofl: 

At any rate, you can work around this by passing a 'User-Agent': 'foo' header to the session put command like so:

```
...
data = {'login': self._login, 'password': self._password}
headers = {'User-Agent': 'foo'}
r = self._session.put(self._api+'/login', headers=headers, json=data)
...
```

No idea how long that fix would last though. I'm guessing they'll find another way to block it. You could also set the 'User-Agent' to mimic a browser like Chrome (ie, 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36'). It might be harder for them to block, but it might be worth figuring out **why** they chose to block it in the first place. Just not sure who to contact on the Sleep IQ side.

**Comment by CCOSTAN** [comment] 2020-11-19 23:49
Could we mimic the app User-Agent?

**Comment by CCOSTAN** [comment] 2020-11-19 23:59
> No idea how long that fix would last though. I'm guessing they'll find another way to block it. You could also set the 'User-Agent' to mimic a browser like Chrome (ie, 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.66 Safari/537.36'). It might be harder for them to block, but it might be worth figuring out **why** they chose to block it in the first place. Just not sure who to contact on the Sleep IQ side.

Looks like that is what the Hubitat folks do. 
```
private def ApiUserAgent() { "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36" }
```
https://community.hubitat.com/t/sleepiq-sleep-number/15053/11

**Comment by ratsputin** [comment] 2020-11-20 01:09
While using that user agent did allow the login to succeed, further API calls appear to fail:

```
Python 3.7.5 (default, Apr 19 2020, 20:18:17)
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from sleepyq import Sleepyq
>>> from pprint import pprint
>>> client = Sleepyq('sleepiq_user', 'sleepiq_pass')
>>> client.login()
True
>>> pprint(client.sleepers())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/srv/homeassistant/venv/lib/python3.7/site-packages/sleepyq/__init__.py", line 130, in sleepers
    r=self.__make_request('/sleeper')
  File "/srv/homeassistant/venv/lib/python3.7/site-packages/sleepyq/__init__.py", line 101, in __make_request
    retry = self.__make_request(url, mode, data, attempt+1)
  File "/srv/homeassistant/venv/lib/python3.7/site-packages/sleepyq/__init__.py", line 101, in __make_request
    retry = self.__make_request(url, mode, data, attempt+1)
  File "/srv/homeassistant/venv/lib/python3.7/site-packages/sleepyq/__init__.py", line 101, in __make_request
    retry = self.__make_request(url, mode, data, attempt+1)
  File "/srv/homeassistant/venv/lib/python3.7/site-packages/sleepyq/__init__.py", line 104, in __make_request
    r.raise_for_status()
  File "/srv/homeassistant/venv/lib/python3.7/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://prod-api.sleepiq.sleepnumber.com/rest/sleeper?_k=xxxxxxxxxxxxx
>>>
```

**Comment by joshdreagan** [comment] 2020-11-20 01:13
> While using that user agent did allow the login to succeed, further API calls appear to fail:
> ...

I would imagine you'd have to set the header on every call.

**Comment by ratsputin** [comment] 2020-11-20 01:28
LOL!  Oh.  Duh.

Let me test...

**Comment by tagno25** [comment] 2020-11-20 01:30
You can just add the user-agent header to the session initialization section
```
...
self._session = requests.Session()
self._session.headers.update({'User-Agent': 'foo'})
self._api = "https://api.sleepiq.sleepnumber.com/rest"
... 
```

**Comment by towerhand** [comment] 2020-11-20 01:32
Can someone please explain how to change the user agent manually in HA?

Edit: that way people can temporarily fix it until it get merged to core.

**Comment by ratsputin** [comment] 2020-11-20 01:35
@tagno25 THANK YOU!  I'm not a python programmer, so that was a terrific help and seems to have fixed the API.

@towerhand I need to test the changes I just made as per tagno25's instructions.

**Comment by ratsputin** [comment] 2020-11-20 01:43
Okay, the fix recommended by @tagno25 addressed the issue with HA.  I'm running a python venv so I can only provide instructions on how to manually fix it that way.  If you're running a different flavor of HA, you'll have to find the library yourself.

In my case, I found the sleepyq library in `~homeassistant/venv/lib/python3.7/site-packages/sleepyq`.  You'll have to find the library directory in your own hierarchy yourself.

In that directory, there's an `__init__.py` file you need to edit.  Look for this block of code around line 80:

```
class Sleepyq:
    def __init__(self, login, password):
        self._login = login
        self._password = password
        self._session = requests.Session()
        self._api = "https://prod-api.sleepiq.sleepnumber.com/rest"
```
After the `self._session = requests.Session()`, insert the following line lining it up with the line above:
```
self._session.headers.update({'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36'})
```
The end result should be as follows:
```
class Sleepyq:
    def __init__(self, login, password):
        self._login = login
        self._password = password
        self._session = requests.Session()
        self._session.headers.update({'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/28.0.1500.95 Safari/537.36'})
        self._api = "https://prod-api.sleepiq.sleepnumber.com/rest"
```

**Comment by horrorshow21** [comment] 2020-11-20 02:32
sleepyq directory if your using docker (I accessed via Portainer console)
`/usr/local/lib/python3.8/site-packages/sleepyq/__init__.py`
Tested working. BIG thanks to those above for finding the issue and posting a manual fix.

**Comment by towerhand** [comment] 2020-11-20 03:03
I found a different approach.

1. Logged in to SSH via Community SSH & Web Terminal add-on. (protection mode off)
2. Executed command: 
```docker exec -it homeassistant vi /usr/local/lib/python3.8/site-packages/sleepyq/__init__.py```
3. Added the line as explained by ratsputin.
4. Restarted HA.

Really appreciate the quick fix.

**Comment by jpenrodST** [comment] 2020-11-20 03:13
Yep thank you for the quick fix, confirmed it worked for me as well.

**Comment by joshdreagan** [comment] 2020-11-20 03:20
I'll submit a PR tomorrow morning so we can get the fix merged and (hopefully) into the next release. In the meantime, manually updating your local copy of the python source file seems to be a decent workaround.

**Closed as completed** 2020-11-20 05:50 UTC

**Comment by mbrunton77** [comment] 2020-11-20 15:08
Thanks for the fix!!!

**Comment by tedmundson** [comment] 2020-12-14 05:18
Sleep numberIQ  has stopped working again any one have a fix

**Comment by ratsputin** [comment] 2020-12-14 12:06
SleepIQ is apparently having significant issues on their side due to load from unauthorized API calls.  Their service has become unreliable but eventually works.

It’s now taking several minutes (10 or more) to detect presence.
